const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
function setup(status=201){const els=new Map(),calls=[];const values={nombre:'Monstera',id_categoria:'1',tamano:'Mediana',nivel_cuidado:'Bajo',necesidad_luz:'Indirecta',necesidad_agua:'Semanal',estado_salud:'Excelente',ubicacion:'San Salvador',descripcion:''};const photo={type:'image/jpeg',size:100};
const el=id=>{if(!els.has(id))els.set(id,{hidden:true,handlers:{},options:[{}],files:[photo],value:'',elements:{namedItem:n=>({value:values[n]})},addEventListener(k,v){this.handlers[k]=v;},append(v){this.options.push(v);},reportValidity:()=>true,reset(){},scrollIntoView(){},focus(){}});return els.get(id);};
class Form{constructor(){this.data=new Map(Object.entries(values));this.data.set('fotografia',photo);}get(k){return this.data.get(k);}set(k,v){this.data.set(k,v);}delete(k){this.data.delete(k);}}
const ctx={document:{getElementById:el,createElement:()=>({})},window:{ADOPPLANT_API_URL:'https://api.example/api',addEventListener(){},location:{replace(){}}},sessionStorage:{getItem:k=>k==='token'?'test-token':null,removeItem(){},setItem(){}},FormData:Form,AbortController,setTimeout,clearTimeout,URL,async fetch(url,options){calls.push({url,options});const create=['POST','PATCH'].includes(options.method);return {status:create?status:200,ok:!create||status===201,json:async()=>create?(status===201?{id_planta:4,nombre:'Monstera'}:{detail:'No se pudo guardar la fotografía'}):url.endsWith('/usuarios/me')?{id_usuario:1}:[{id_categoria:1,nombre:'Interior',estado:'ACTIVA'}]};}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../views/publicar.js'),'utf8'),ctx);return {ctx,el,calls};}
const tick=()=>new Promise(r=>setImmediate(r));
test('envía fotografía y datos con autenticación y confirma creación',async()=>{const s=setup();await tick();await s.el('publishForm').handlers.submit({preventDefault(){},currentTarget:s.el('publishForm')});const call=s.calls.find(c=>c.options.method==='POST');assert.equal(call.options.headers.Authorization,'Bearer test-token');assert.equal(call.options.headers['Content-Type'],undefined);assert.equal(call.options.body.get('fotografia').type,'image/jpeg');assert.equal(call.options.body.get('necesidad_agua'),'Semanal');assert.equal(s.el('publishSuccess').hidden,false);assert.equal(s.el('publishForm').hidden,true);});
test('no anuncia éxito cuando falla la API',async()=>{const s=setup(503);await tick();await s.el('publishForm').handlers.submit({preventDefault(){},currentTarget:s.el('publishForm')});assert.equal(s.el('publishSuccess').hidden,true);assert.equal(s.el('publishForm').hidden,false);assert.match(s.el('formMessage').textContent,/fotografía/);assert.equal(s.el('publishButton').disabled,false);});
test('rechaza fotografía ausente, formato incorrecto y más de 8 MB',async()=>{const s=setup();await tick();assert.throws(()=>s.ctx.validatePublicationPhoto(null));assert.throws(()=>s.ctx.validatePublicationPhoto({type:'text/plain',size:20}));assert.throws(()=>s.ctx.validatePublicationPhoto({type:'image/png',size:9*1024*1024}));});

test('editar actualiza la publicación y conserva la foto si no hay otra',async()=>{const s=setup();await tick();const event={preventDefault(){},currentTarget:s.el('publishForm')};await s.el('publishForm').handlers.submit(event);s.el('editPublication').handlers.click();s.el('photograph').files=[];await s.el('publishForm').handlers.submit(event);const call=s.calls.find(c=>c.options.method==='PATCH');assert.equal(call.url,'https://api.example/api/plantas/4');assert.equal(call.options.body.get('fotografia'),undefined);assert.equal(s.el('publishSuccess').hidden,false);assert.match(s.el('successTitle').textContent,/actualizada/);});
