const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
function setup({search='?tipo=recibidas',owner=1,user=1,status='PENDIENTE',fail=false}={}){
  const nodes=new Map(),calls=[];
  function node(){return {hidden:true,children:[],options:[{}],handlers:{},value:'',addEventListener(k,v){this.handlers[k]=v;},append(...items){this.children.push(...items);this.options.push(...items);},replaceChildren(...items){this.children=items;},remove(index){this.options.splice(index,1);},showModal(){this.open=true;},close(){this.open=false;}};}
  const el=id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id);};
  const plant={id_planta:7,id_usuario:owner,nombre:'Monstera',estado_planta:'DISPONIBLE',visible:true,eliminada:false};
  const request={id_solicitud:9,id_planta:7,id_adoptante:2,nombre_adoptante:'María González',nombre_planta:'Monstera',mensaje:'Quiero cuidarla en mi hogar.',estado:status,fecha_solicitud:'2026-10-03T12:00:00Z'};
  const context={document:{getElementById:el,createElement:node},window:{ADOPPLANT_API_URL:'https://api.example/api',location:{search,replace(){}}},sessionStorage:{getItem:()=> 'token',removeItem(){}},URL,URLSearchParams,AbortController,setTimeout,clearTimeout,
    async fetch(url,options){calls.push({url,options});const patch=options.method==='PATCH';const data=patch?(fail?{detail:'La solicitud ya cambió'}:{...request,estado:JSON.parse(options.body).estado}):url.endsWith('/usuarios/me')?{id_usuario:user}:url.includes('/plantas/mias?')?[plant]:url.includes('/plantas/')?plant:url.includes('/solicitudes?')?[request]:request;return {status:patch&&fail?409:200,ok:!(patch&&fail),json:async()=>data};}};
  vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../views/solicitudes.js'),'utf8'),context);return {context,el,calls};
}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
test('lista recibidas y filtra por planta con nombre y mensaje reales',async()=>{const s=setup();await tick();assert.equal(s.el('requestsList').hidden,false);assert.match(s.calls.find(c=>c.url.includes('/solicitudes?')).url,/tipo=recibidas/);assert.equal(s.el('requestCards').children.length,1);s.el('requestPlant').value='7';await s.el('requestPlant').handlers.change();assert.match(s.calls.at(-1).url,/id_planta=7/);});
test('confirmación carga la solicitud guardada de quien la envió',async()=>{const s=setup({search:'?tipo=enviadas&vista=enviada&id=9',user:2});await tick();assert.equal(s.el('sentConfirmation').hidden,false);assert.match(s.el('confirmationText').textContent,/Monstera/);assert.equal(s.el('confirmationState').textContent,'● Pendiente');});
test('otra cuenta no ve confirmación de envío como propia',async()=>{const s=setup({search:'?tipo=enviadas&vista=enviada&id=9'});await tick();assert.equal(s.el('sentConfirmation').hidden,true);assert.match(s.el('requestsStatus').textContent,/no corresponde/);});
test('donante acepta después de confirmar y no puede decidir otra vez',async()=>{const s=setup({search:'?tipo=recibidas&id=9'});await tick();assert.equal(s.el('decisionActions').hidden,false);s.el('acceptRequest').handlers.click();assert.equal(s.el('decisionDialog').open,true);assert.equal(s.calls.filter(c=>c.options.method==='PATCH').length,0);await s.el('confirmDecision').handlers.click();await s.el('confirmDecision').handlers.click();const posts=s.calls.filter(c=>c.options.method==='PATCH');assert.equal(posts.length,1);assert.deepEqual(JSON.parse(posts[0].options.body),{estado:'ACEPTADA'});assert.equal(s.el('detailRequestState').textContent,'✓ Aceptada');assert.equal(s.el('decisionActions').hidden,true);});
test('adoptante y solicitudes decididas no permiten decisión de donante',async()=>{for(const options of [{user:2},{status:'ACEPTADA'}]){const s=setup({search:'?tipo=enviadas&id=9',...options});await tick();assert.equal(s.el('decisionActions').hidden,true);s.el('rejectRequest').handlers.click();await s.el('confirmDecision').handlers.click();assert.equal(s.calls.filter(c=>c.options.method==='PATCH').length,0);}});
test('rechaza con estado correcto y muestra conflictos sin anunciar éxito',async()=>{for(const fail of [false,true]){const s=setup({search:'?tipo=recibidas&id=9',fail});await tick();s.el('rejectRequest').handlers.click();await s.el('confirmDecision').handlers.click();assert.equal(JSON.parse(s.calls.at(-1).options.body).estado,'RECHAZADA');if(fail){assert.match(s.el('decisionStatus').textContent,/ya cambió/);assert.equal(s.el('detailRequestState').textContent,'● Pendiente');}else assert.equal(s.el('detailRequestState').textContent,'× Rechazada');}});
